type User {
  username: String! @unique
}

input CreateUserInput {
  username: String!
  password: String!
}

input LoginUserInput {
  username: String!
  password: String!
}

type Mutation {
  createUser(input: CreateUserInput): User! @resolver(name: "create_user")
  loginUser(input: LoginUserInput): String! @resolver(name: "login_user")
}