name: Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Configure environment
      run: |
        cp .env.example .env
        sed -i .bak 's/FAUNADB_TEST_ADMIN_SECRET=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/FAUNADB_TEST_ADMIN_SECRET=$FAUNADB_TEST_ADMIN_SECRET/g' .env
    - name: Install
      run: npm install
    - name: Test
      run: npm test